FROM astiunov/data-science
MAINTAINER Alexander Tiunov <astiunov@yandex-team.ru>

RUN mkdir -p /srv
COPY install-jupyter.sh run-jupyter.sh /srv/
COPY jupyter_req.yml ./
ADD https://raw.githubusercontent.com/jupyterhub/jupyterhub/master/scripts/jupyterhub-singleuser /usr/local/bin/jupyterhub-singleuser
RUN chmod 755 /usr/local/bin/jupyterhub-singleuser && /srv/install-jupyter.sh

EXPOSE 8888

RUN useradd -m -s /bin/bash main

USER main
ENV HOME /home/main
ENV SHELL /bin/bash
ENV USER main
WORKDIR /home/main/

USER root
RUN ln -s /usr/miniconda3 /home/main/anaconda && chown -R main:main /home/main

USER main

CMD ["sh", "/srv/run-jupyter.sh"]
